### ISSUE TITLE
Put routes in a class method

### ISSUE THREAD

**Issue by jnicklas** [garybernhardt/raptor#16]
It would be cool if we didn't have to load Raptor in order to require a particular resource.

Currently we have this:

``` ruby
module Posts
  Routes = Raptor.routes(self) do
    ...
  end
```

if we change this to:

``` ruby
module Posts
  def self.routes
    Raptor.routes(self) do
      ...
    end
  end
```

it's a little more verbose, but we don't have to have Raptor defined in order to load this resource.

What do you think?

**Comment by garybernhardt** [comment]
+1! Pull request? :)

**Comment by jnicklas** [comment]
If I find the time I'll try to work figure it out. Just wanted to hear what you thought about the idea first.

**Comment by tom-pang** [comment]
See issue #20.

**Comment by garybernhardt** [comment]
#20 moved the routes to a class method, but I apparently moved them back to a constant in the great module inversion. They now live at MyApp::Routes, with the idea being that you'll define them either in an app.rb or in a source file dedicated to routes. This seems to solve the problem of loading app components without Raptor installed. Thoughts?

**Comment by tom-pang** [comment]
I'm happy with them because of the module inversion. Seems if you want to be able to load non-http parts of your app without loading raptor, it can go in separate files. Also, routes as a class method has symmetry problems.

**Comment by garybernhardt** [comment]
I'm sold.
