### ISSUE TITLE
PUT method does not work

### ISSUE THREAD

**Issue by felipeelias** [garybernhardt/raptor#24]
Following the example in `/examples` I couldn't make the update action work. Here's the form:

``` html
# edit.html.erb
<form method="POST" action="/posts/<%= id %>">
  <input type="hidden" name="_method" value="PUT" />
  Title: <input type="text" name="title" value="<%= title %>" />
  <input type="submit">
</form>
```

I managed to make this work by including the `Rack::MethodOverride` in `config.ru` file. I wonder how this could be handled by default in raptor.

**Comment by tom-pang** [comment]
we never got round to implementing put/delete over the method hidden input hack, so it's unsurprising that this is broken ;)

**Comment by garybernhardt** [comment]
We're working on this in #25.
