### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by danawoodman** [garybernhardt/raptor#60]
This looks pretty interesting, but seems to be abandoned. Will there be any more work on it or should I move on my merry way?

![Is it alive?](http://f.cl.ly/items/3M3B081Y0p343B3z3S2p/Image%202013.02.22%204:14:01%20PM.png)

**Comment by garybernhardt** [comment]
I don't currently build web apps, so I'm not using Raptor. I don't know whether @tcrayford is.

**Comment by danawoodman** [comment]
Gotcha. Listened to your thoughtbot interview the other day -- which was excellent -- and thought I'd check this out. 

Loving DestroyAllSoftware!

**Comment by garybernhardt** [comment]
Thanks. :)

**Comment by tom-pang** [comment]
I don't write ruby outside of the job these days, so I guess raptor is dead.
